name: serverchan_sdk
description: A Dart SDK for sending messages via Server Chan.
version: 1.0.6
homepage: https://sct.ftqq.com
repository: https://github.com/easychen/serverchan-sdk
issue_tracker: https://github.com/easychen/serverchan-sdk/issues
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ^0.13.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.11.0

# Optional section for dart analysis and formatting rules.
# This ensures a consistent code style.
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

flutter:
  uses-material-design: false
